# name=input("请输入您的姓名:")
# print(f"欢迎您,{name}")
# code=input("请输入密码:")
# 余额=10000
# print(f'''
# 密码正确
# 账号余额为:{余额}
# ''')
# 取款金额=input("请输入取款金额:")
# print("账号余额为:%d"%(余额-int(取款金额)))
# a=input("")
# b=input("")
# print("两数之和为:%d"%(int(a)+int(b)))